# Generated by Django 6.0.4 on 2026-04-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Blusa', 'Blusa'), ('Vestido', 'Vestido'), ('Pantalón', 'Pantalón'), ('Zapatos', 'Zapatos'), ('Accesorios', 'Accesorios')], max_length=50)),
                ('talla', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('vendidos', models.IntegerField(default=0)),
                ('imagen', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
