# Generated by Django 5.0 on 2026-05-06 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_categoria_remove_producto_vendidos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('correccion', 'Correccion de stock')], max_length=15)),
                ('motivo', models.CharField(choices=[('compra_proveedor', 'Compra a proveedor'), ('devolucion_cliente', 'Devolución de cliente'), ('venta_manual', 'Venta manual'), ('producto_dañado', 'Producto dañado'), ('perdida', 'Pérdida'), ('robo', 'Robo'), ('conteo_fisico', 'Conteo físico'), ('correccion_manual', 'Corrección manual')], max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('stock_anterior', models.PositiveIntegerField()),
                ('stock_nuevo', models.PositiveIntegerField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='productos.producto')),
            ],
        ),
    ]
