# Generated by Django 5.0 on 2026-05-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_movimientoinventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='motivo',
            field=models.CharField(blank=True, choices=[('compra_proveedor', 'Compra a proveedor'), ('devolucion_cliente', 'Devolución de cliente'), ('venta_manual', 'Venta manual'), ('producto_dañado', 'Producto dañado'), ('perdida', 'Pérdida'), ('robo', 'Robo'), ('conteo_fisico', 'Conteo físico'), ('correccion_manual', 'Corrección manual'), ('devolucion_proveedor', 'Devolución a proveedor')], max_length=100, null=True),
        ),
    ]
