# Generated by Django 5.0.14 on 2026-05-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_producto_imagen_imagefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='motivo',
            field=models.CharField(blank=True, choices=[('compra_proveedor', 'Compra a proveedor'), ('devolucion_cliente', 'Devolucion de cliente'), ('venta_manual', 'Venta manual'), ('venta_sistema', 'Venta del sistema'), ('producto_danado', 'Producto danado'), ('perdida', 'Perdida'), ('robo', 'Robo'), ('conteo_fisico', 'Conteo fisico'), ('correccion_manual', 'Correccion manual'), ('devolucion_proveedor', 'Devolucion a proveedor')], max_length=100, null=True),
        ),
    ]
